In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.colors as colors
pio.templates.default="plotly_white"

In [2]:
df=pd.read_csv('sales.csv')
df.head()

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Unit_Price,Discount_Pct,Discount_Amount,Revenue,Net_Revenue,Payment_Method,Order_Status
0,100333,2026-01-01,6139,Bengaluru,Mouse,Accessories,2,906.60,5,90.66,1813.20,1722.54,Credit Card,Shipped
1,100493,2026-01-01,5217,Delhi,Printer,Office,1,25974.74,10,2597.47,25974.74,23377.27,Debit Card,Delivered
2,100517,2026-01-01,5887,Delhi,Backpack,Accessories,3,1343.21,20,805.93,4029.63,3223.70,Cash on Delivery,Delivered
3,100577,2026-01-01,5165,Bengaluru,Mouse,Accessories,2,948.23,0,0.00,1896.46,1896.46,Debit Card,Delivered
4,100646,2026-01-01,5954,Kolkata,Tablet,Electronics,2,12699.04,0,0.00,25398.08,25398.08,Credit Card,Delivered

In [3]:
df.tail()

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Unit_Price,Discount_Pct,Discount_Amount,Revenue,Net_Revenue,Payment_Method,Order_Status
10015,102257,2026-01-12,6222,Hyderabad,Headphones,Electronics,1,5808.92,25,1452.23,5808.92,4356.69,Debit Card,Shipped
10016,108063,2026-04-07,5858,Ahmedabad,Monitor,Electronics,3,17335.13,15,7800.81,52005.39,44204.58,Credit Card,Delivered
10017,106896,2026-06-13,5111,Bengaluru,Monitor,Electronics,1,19407.10,20,3881.42,19407.10,15525.68,UPI,Delivered
10018,106686,2026-03-25,5827,Mumbai,Backpack,Accessories,1,2728.88,0,0.00,2728.88,2728.88,UPI,Delivered
10019,103362,2026-08-30,7245,Mumbai,Keyboard,Accessories,3,990.13,10,297.04,2970.39,2673.35,UPI,Delivered

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10020 entries, 0 to 10019
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         10020 non-null  int64
 1   Order_Date       10020 non-null  object
 2   Customer_ID      10020 non-null  int64
 3   City             9994 non-null   object
 4   Product          10020 non-null  object
 5   Category         10020 non-null  object
 6   Quantity         10020 non-null  int64
 7   Unit_Price       9980 non-null   float64
 8   Discount_Pct     10020 non-null  int64
 9   Discount_Amount  10020 non-null  float64
 10  Revenue          10020 non-null  float64
 11  Net_Revenue      10020 non-null  float64
 12  Payment_Method   10020 non-null  object
 13  Order_Status     10020 non-null  object
dtypes: float64(4), int64(4), object(6)
memory usage: 1.1+ MB

In [6]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

### Cleaning of the dataset

In [7]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
City               26
Product             0
Category            0
Quantity            0
Unit_Price         40
Discount_Pct        0
Discount_Amount     0
Revenue             0
Net_Revenue         0
Payment_Method      0
Order_Status        0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
City               0
Product            0
Category           0
Quantity           0
Unit_Price         0
Discount_Pct       0
Discount_Amount    0
Revenue            0
Net_Revenue        0
Payment_Method     0
Order_Status       0
dtype: int64

In [10]:
df.shape

(9954, 14)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9954 entries, 0 to 10019
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         9954 non-null   int64
 1   Order_Date       9954 non-null   datetime64[ns]
 2   Customer_ID      9954 non-null   int64
 3   City             9954 non-null   object
 4   Product          9954 non-null   object
 5   Category         9954 non-null   object
 6   Quantity         9954 non-null   int64
 7   Unit_Price       9954 non-null   float64
 8   Discount_Pct     9954 non-null   int64
 9   Discount_Amount  9954 non-null   float64
 10  Revenue          9954 non-null   float64
 11  Net_Revenue      9954 non-null   float64
 12  Payment_Method   9954 non-null   object
 13  Order_Status     9954 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(4), object(5)
memory usage: 1.1+ MB

In [12]:
df = df.drop_duplicates()

In [15]:
total_sales = df['Net_Revenue'].sum()
average_transaction = df['Net_Revenue'].mean()

In [16]:
duplicates = df.duplicated().sum()

if duplicates > 0:
    print("WARNING:", duplicates, "duplicates found")

In [17]:
if (df["Quantity"] <= 0).any():
    print("WARNING: Invalid quantity detected")

In [23]:
! pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.13-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2-2.9.13-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ---------------------------------------- 2.8/2.8 MB 14.0 MB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.13

In [26]:
#### Connection with postreqsql

from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Vikrantp1@@localhost:5432/sales_automation"
)

In [18]:
if (df["Net_Revenue"] < 0).any():
    print("WARNING: Negative revenue detected")

In [19]:
!pip install pandas numpy sqlalchemy psycopg-binary

Requirement already satisfied: pandas in c:\users\vikra\appdata\roaming\python\python313\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\vikra\appdata\roaming\python\python313\site-packages (2.3.5)
Requirement already satisfied: sqlalchemy in c:\users\vikra\anaconda3\lib\site-packages (2.0.39)
Collecting psycopg-binary
  Downloading psycopg_binary-3.3.6-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vikra\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vikra\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vikra\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\vikra\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vikra\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\vikra\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading psycopg_binary-3.3.6-cp313-cp313-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.7 MB 5.6 MB/s eta 0:00:01
   ------------------------------------- -- 3.4/3.7 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 12.3 MB/s eta 0:00:00
Installing collected packages: psycopg-binary
Successfully installed psycopg-binary-3.3.6

In [27]:
df.to_csv("cleaned_sales.csv", index=False)